### ISSUE TITLE
Level 3 Solutions

### ISSUE THREAD

**Issue by avaamini** [shilpamagrawal15/cookingmamas#6]
To avoid having to account for a potentially large number of Level 3 solutions (which we currently don’t know) we could change the wording of the objective to “make enough entrees for exactly 27 people, make enough dessert for exactly 27 people”. if any objections let me know, otherwise i’ll change it. 
@hejanew @shilpamagrawal15

**Comment by hejanew** [comment]
Actually, I think there is only one unique solution. I closed the comment I made about users being told they didn't meet the objective if they made more than enough because it is not possible to make more than the exact ask of 27 entrees. The reason I previously thought you could make more than 27 entrees and be correct was because the listeners weren't working correctly, so the amount in the cabinet was not subtracting correctly and there appeared to be more of an ingredient remaining than there actually was. So this is actually a listener issue, not a feedback issue
@shilpamagrawal15 @apsoleimany

**Comment by hejanew** [comment]
@apsoleimany The solution you suggested with 2 cakes and 7 cookies does not work because there is not enough lemon juice. The only solutions are:
17+ cookies (up to 50)
1 cake
12 asparagus
15 linguini

And the feedback actually currently gives correct feedback to these solutions

**Comment by avaamini** [comment]
@hejanew yeah i realized that second solution doesn't work-- also not enough vanilla. great!

**Comment by shilpamagrawal15** [comment]
Is this issue closed? If so, we can mark it as closed.
